apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGd2Z3pnNG8w
  CLOUDINARY_KEY: NzQxMzc2NTY4MjcyMTQy
  CLOUDINARY_SECRET: U1FDLTdEOF91eDhOOTlLUFUyRW9Rd2JZUVJN
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laR2xzYkdsa1pYWnZjSE15SWl3aVlTSTZJbU50YmpkdmVURTVZekF5T0dFeWNuTTVibWh4ZEd3MVl6UWlmUS5IQmVJVHdKWlVqMV82T2NuLWMySW1R
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAudGVpbG5hci5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
